//Issues
export const SET_ISSUES = 'SET_ISSUES';
export const SET_ISSUES_FAIL = 'SET_ISSUES_FAIL';

export const SET_ISSUE = 'SET_ISSUE';
export const SET_ISSUE_FAIL = 'SET_ISSUE_FAIL';

export const POST_ISSUE = 'POST_ISSUE';
export const POST_ISSUE_SUCCESS = 'POST_ISSUE_SUCCESS';
export const POST_ISSUE_FAIL = 'POST_ISSUE_FAIL';

export const DELETE_ISSUE = 'DELETE_ISSUE';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';
export const DELETE_ISSUE_FAIL = 'DELETE_ISSUE_FAIL';

export const UPDATE_ISSUE = 'UPDATE_ISSUE';
export const UPDATE_ISSUE_SUCCESS = 'UPDATE_ISSUE_SUCCESS';
export const UPDATE_ISSUE_FAIL = 'UPDATE_ISSUE_FAIL';

export const SUBSCRIPTION_ISSUE_SUCCESS = 'SUBSCRIPTION_ISSUE_SUCCESS';
export const SUBSCRIPTION_ISSUE_FAIL = 'SUBSCRIPTION_ISSUE_FAIL';

export const UNSUBSCRIPTION_ISSUE_SUCCESS = 'UNSUBSCRIPTION_ISSUE_SUCCESS';
export const UNSUBSCRIPTION_ISSUE_FAIL = 'UNSUBSCRIPTION_ISSUE_FAIL';

//Offers
export const SET_OFFERS = 'SET_OFFERS';
export const SET_OFFERS_FAIL = 'SET_OFFERS_FAIL';

export const SET_OFFER = 'SET_OFFER';
export const SET_OFFER_FAIL = 'SET_OFFER_FAIL';

export const POST_OFFER = 'POST_OFFER';
export const POST_OFFER_SUCCESS = 'POST_OFFER_SUCCESS';
export const POST_OFFER_FAIL = 'POST_OFFER_FAIL';

export const DELETE_OFFER = 'DELETE_OFFER';
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS';
export const DELETE_OFFER_FAIL = 'DELETE_OFFER_FAIL';

export const UPDATE_OFFER = 'UPDATE_OFFER';
export const UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS';
export const UPDATE_OFFER_FAIL = 'UPDATE_OFFER_FAIL';


//Issues
export const SET_TICKETS = 'SET_TICKETS';
export const SET_TICKETS_FAIL = 'SET_TICKETS_FAIL';

export const SET_TICKET = 'SET_TICKET';
export const SET_TICKET_FAIL = 'SET_TICKET_FAIL';

export const POST_TICKET = 'POST_TICKET';
export const POST_TICKET_SUCCESS = 'POST_TICKET_SUCCESS';
export const POST_TICKET_FAIL = 'POST_TICKET_FAIL';

export const DELETE_TICKET = 'DELETE_TICKET';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL';

export const UPDATE_TICKET = 'UPDATE_TICKET';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
export const UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL';

//Notes
export const SET_NOTE = 'SET_NOTE';
export const SET_NOTE_FAIL = 'SET_NOTE_FAIL';

export const POST_NOTE = 'POST_NOTE';
export const POST_NOTE_SUCCESS = 'POST_NOTE_SUCCESS';
export const POST_NOTE_FAIL = 'POST_NOTE_FAIL';

export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_FAIL = 'DELETE_NOTE_FAIL';

export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';

// Auth
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// User
export const INIT_USER = 'INIT_USER';
export const INIT_USER_SUCCESS = 'INIT_USER_SUCCESS';
export const INIT_USER_FAIL = 'INIT_USER_FAIL';

export const SET_USERS = 'SET_USERS';
export const SET_USERS_FAIL = 'SET_USERS_FAIL';

export const SUBSCRIBE_USER_SUCCESS = 'SUBSCRIBE_USER_SUCCESS';
export const SUBSCRIBE_USER_FAIL = 'SUBSCRIBE_USER_FAIL';

export const UNSUBSCRIBE_USER_SUCCESS = 'UNSUBSCRIBE_USER_SUCCESS';
export const UNSUBSCRIBE_USER_FAIL = 'UNSUBSCRIBE_USER_FAIL';

export const GRANT_TICKET_SUCCESS = 'GRANT_TICKET_SUCCESS';
export const GRANT_TICKET_FAIL = 'GRANT_TICKET_FAIL';

export const UNGRANT_TICKET_SUCCESS = 'UNGRANT_TICKET_SUCCESS';
export const UNGRANT_TICKET_FAIL = 'UNGRANT_TICKET_FAIL';

export const SET_USER_ISSUES = 'SET_USER_ISSUES';
export const SET_USER_TICKETS = 'SET_USER_TICKETS';
export const SET_USER_OFFERS = 'SET_USER_OFFERS';
export const SET_USER_DATA_FAIL = 'SET_USER_DATA_FAIL';
